config/routes.rb
ElectionCounter::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  resources :votes

  # Routes for API Demo
  ################################################################################
  namespace :apidemo, :only => [] do
    get :graph, :to => :api_v1_demo_graphs
    get :rawdata, :to => :api_v1_demo_rawdata
  end

  # API Namespace
  ################################################################################
  namespace :api, defaults: {format: 'json'} do
    # Version 1 of API
    namespace :v1 do

      ################################################################################
      #
      #  All Responses bellow this point returns a collection of Data in JSON Format
      #
      # GET   /api/v1/rawdata/votedistricts
      # GET   /api/v1/rawdata/districts
      # 
      resources :rawdata, :only => [] do
        collection do
          get 'votedistricts'
          get 'districts'
        end # collection
      end # resources

      ################################################################################
      #
      #       All Responses bellow this point return one or multiple HTTP Links
      #                   which can be included directly as image
      #
      # GET    /api/v1/graph/pie/type1/:resolution
      # GET    /api/v1/graph/pie/type1/
      #
      # GET    /api/v1/graph/bar/type1/:resolution
      # GET    /api/v1/graph/bar/type1/
      #
      # GET    /api/v1/graph/bar/type2/:resolution
      # GET    /api/v1/graph/bar/type2/
      #
      resources :graph, :only => [] do
        collection do
          # Bar Charts
          namespace :bar do
            get 'type1/:resolution/', :controller => :graphs, :action => :graph_bar_t1      # optional with resolution
            get 'type1/', :controller => :graphs, :action => :graph_bar_t1
          end
          # Pie Charts
          namespace :pie do
            get 'type1/:resolution', :controller => :graphs, :action => :graph_pie_type1    # optional with resolution
            get 'type1/', :controller => :graphs, :action => :graph_pie_type1

            get 'type2/:resolution/', :controller => :graphs, :action => :graph_pie_type2   # optional with resolution
            get 'type2/', :controller => :graphs, :action => :graph_pie_type2
          end 
        end # collection 
      end # graph
      ################################################################################

    end # v1
  end # api

  root :to => "apidemo#api_v1_demo_graphs"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ElectionCounter" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li class="brand">ElectionCounter</li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">API<b class="caret"></b></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Graphen", apidemo_graph_path %></li>
                  <li><%= link_to "Rohdaten", apidemo_rawdata_path %></li>
                </ul>
              </li>
              <% if user_signed_in? %>
                <li><%= link_to "Unterstützungserklärungen", "/votes"  %></li>
                <li><%= link_to "Admin", "/admin/"  %></li>
                <li><%=  link_to "Ausloggen", destroy_user_session_path, :method => :delete %></li>
              <% else %>
                <li><%=  link_to "Einloggen", new_user_session_path %></li>
                <li><%=  link_to "Registrieren", new_user_registration_path %></li>
              <% end %>
            </ul>

            <ul class="nav pull-right">
              <li>
                <a href="https://github.com/moregeek/ElectionCounter/issues">Fehler gefunden?</a>
              </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span12">

             <% unless flash[:notice].blank? %>
               <div class="alert alert-info">
                 <%= content_tag :div, flash[:notice] %>
               </div>
             <% end %>

             <% unless flash[:error].blank? %>
               <div class="alert alert-error">
                 <%= content_tag :div, flash[:error] %>
               </div>
             <% end %>

             <% unless flash[:alert].blank? %>
               <div class="alert alert-info">
                 <%= content_tag :div, flash[:alert] %>
               </div>
             <% end %>

             <%= yield %>
          </div>
          
        </div><!--/row-->

      <footer>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>